on:
  push:
    branches: [ main ]
name: 🚀 Deploy website on push
jobs:
  deploy:
    name: 🎉 Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: rsync deployments
      uses: burnett01/rsync-deployments@5.2.1
      with:
        switches: -avzr --delete --exclude=".git" --exclude=".github"
        path: /
        remote_path: /var/www/html/develop-v3
        remote_host: https://monev-stunting.bappenas.go.id/
        remote_user: monev-stunting
        remote_key: ${{ secrets.DEPLOY_KEY }}
