on:
  push:
    branches: [ main ]
name: 🚀 Deploy website on push
jobs:
  web-deploy:
    name: 🎉 Auto Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2.3.2
    - name: rsync deployments
    # You may pin to the exact commit or the version.
    # uses: contention/rsync-deployments@980b08d70e94c4ac0169ee5c5acc9ace2fe8ccd4
      uses: contention/rsync-deployments@v1.0.0
