on: [push]

jobs:
    deploy_job:
      runs-on: ubuntu-latest
      name: build&deploy
      steps:
        # To use this repository's private action, you must check out the repository
        - name: Checkout
          uses: actions/checkout@v2


        - name: deploy file to server
          uses: wlixcc/SFTP-Deploy-Action@v1.2.4
          with:
            username: 'root'
            server: '103.97.102.37'
            ssh_private_key: '${{ secrets.DEPLOY_KEY }}'
            local_path: './*'
            remote_path: '/var/www/html/develop-v3'
            sftpArgs: '-o ConnectTimeout=5'
