name: DEPLOY
on:
  push:
    branches:
    - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@4.3.3
      with:
        server:  103.97.102.37
        username: monev-stunting
        protocol: ftps
        port: 22
        password: w5KDLPafChH746r
        server-dir: /var/www/html/xxx/stunting-fe-v3/
