on: push
name: 🚀 Deploy website on push

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
      
    
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@3.1.2
      with:
        server: 103.97.102.37
        username: monev-stunting
        password: w5KDLPafChH746r
        protocol: ftps
        port: 22
