on:
  push:
    branches: [ main ]
name: 🚀 Deploy website on push

  workflow "All pushes" {
    on = "push"
    resolves = ["Deploy to Staging"]
  }

  action "Deploy to Staging" {
    uses = "contention/action-rsync-deploy@master"
    secrets = ["DEPLOY_KEY"]
    args = ["-avzr --delete", "--exclude .htaccess --exclude .git", "monev-stunting@103.97.102.37:/var/www/html/develop-v3/"]
  } 
